VirtoCommerce/vc-module-content

VirtoCommerce.ContentModule.Web/Controllers/Api/ContentController.cs
=> Caching added to pages count

VirtoCommerce.ContentModule.Web/Scripts/blades/pages/edit-blog.js
create folder blog before create default blog post
=> FIX Inconsistencies when adding a blog in admin interface

src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/edit-blog.js
Fix error when creating new blog.
=> VP-2085: Fix error when creating new blog.

src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.js
Fix preview button URL string forming.
=> VP-2064: Fix preview button URL string forming.

src/VirtoCommerce.ContentModule.Web/Scripts/blades/menu/menu-link-list.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/menu/menu-link-list.tpl.html, src/VirtoCommerce.ContentModule.Web/package-lock.json
https://virtocommerce.atlassian.net/browse/VP-2062
=> VP-2062: Fix menu linklists form validation

src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.tpl.html
https://virtocommerce.atlassian.net/browse/VP-2789
=> VP-2789: Fix layout of page-detail blade

src/VirtoCommerce.ContentModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VP-3107
=> VP-3107: Set relative iconUrl

src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/pages-list.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/themes/asset-list.js
https://virtocommerce.atlassian.net/browse/VP-2069
=> VP-2069: Fix endless loading of blade

VirtoCommerce.ContentModule.Web/Scripts/blades/menu/menu-link-list.js
=> VP-2082: Fix context menu behaviour on links delete

src/VirtoCommerce.ContentModule.Web/Controllers/Api/ContentController.cs, src/VirtoCommerce.ContentModule.Web/VirtoCommerce.ContentModule.Web.csproj
"Active theme: default" is never changes on content module blade
Receive actual theme name for store
=> VP-1819: Show active theme in the blade

src/VirtoCommerce.ContentModule.Web/Scripts/blades/themes/theme-detail.js
https://virtocommerce.atlassian.net/browse/VP-2077
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.
=> VP-2077: Fix simplify and fix logic for link calculation

VirtoCommerce.ContentModule.Tests/Validators/ContentFolderValidatorTests.cs, VirtoCommerce.ContentModule.Tests/Validators/ValidatorTestsHelper.cs, VirtoCommerce.ContentModule.Tests/VirtoCommerce.ContentModule.Tests.csproj, VirtoCommerce.ContentModule.sln, src/VirtoCommerce.ContentModule.Web/Controllers/Api/ContentController.cs, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/pages-list.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/themes/asset-list.js, src/VirtoCommerce.ContentModule.Web/Validators/ContentFolderValidator.cs, src/VirtoCommerce.ContentModule.Web/VirtoCommerce.ContentModule.Web.csproj
https://virtocommerce.atlassian.net/browse/VP-4566
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.
=> VP-4566 Fix: add validation for page creating operation

src/VirtoCommerce.ContentModule.Web/Controllers/Api/ContentController.cs, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/pages-list.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/themes/asset-list.js
https://virtocommerce.atlassian.net/browse/VP-4566
https://virtocommerce.atlassian.net/browse/VP-1975
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.
=> VP-4566: Change error contract for UI interceptor

src/VirtoCommerce.ContentModule.Web/Scripts/blades/content-main.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/menu/link-lists.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/menu/menu-link-list.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/edit-blog.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/store-url-list.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/themes/asset-detail.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/themes/asset-list.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/themes/asset-upload.js
=> VP-6864: Fix header icon

src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/pages-list.js
=> VP-6864__Fix_header_icon

VirtoCommerce.ContentModule.Tests/VirtoCommerce.ContentModule.Tests.csproj, src/VirtoCommerce.ContentModule.Azure/VirtoCommerce.ContentModule.Azure.csproj, src/VirtoCommerce.ContentModule.Core/VirtoCommerce.ContentModule.Core.csproj, src/VirtoCommerce.ContentModule.Data/VirtoCommerce.ContentModule.Data.csproj, src/VirtoCommerce.ContentModule.FileSystem/VirtoCommerce.ContentModule.FileSystem.csproj, src/VirtoCommerce.ContentModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-207
=> PT-207: Enable Source link support

src/VirtoCommerce.ContentModule.Web/Scripts/blades/content-main.js
https://virtocommerce.atlassian.net/browse/PT-1224
=> PT-1224: Update content-main.js

src/VirtoCommerce.ContentModule.Azure/AzureContentBlobStorageProvider.cs, src/VirtoCommerce.ContentModule.Azure/AzureContentBlobStorageProviderFactory.cs, src/VirtoCommerce.ContentModule.Azure/VirtoCommerce.ContentModule.Azure.csproj, src/VirtoCommerce.ContentModule.Core/VirtoCommerce.ContentModule.Core.csproj, src/VirtoCommerce.ContentModule.Data/VirtoCommerce.ContentModule.Data.csproj, src/VirtoCommerce.ContentModule.FileSystem/FileSystemContentBlobStorageProvider.cs, src/VirtoCommerce.ContentModule.FileSystem/FileSystemContentBlobStorageProviderFactory.cs, src/VirtoCommerce.ContentModule.FileSystem/VirtoCommerce.ContentModule.FileSystem.csproj, src/VirtoCommerce.ContentModule.Web/Scripts/blades/themes/asset-upload.js, src/VirtoCommerce.ContentModule.Web/VirtoCommerce.ContentModule.Web.csproj, src/VirtoCommerce.ContentModule.Web/module.manifest
PT-3725: Bump platform up to 3.76 to deliver PR-3724
https://virtocommerce.atlassian.net/browse/PT-3724
=> PT-3725: Bump platform up to 3.76 to deliver PR-3724

src/VirtoCommerce.ContentModule.Azure/VirtoCommerce.ContentModule.Azure.csproj, src/VirtoCommerce.ContentModule.Core/VirtoCommerce.ContentModule.Core.csproj, src/VirtoCommerce.ContentModule.Data/VirtoCommerce.ContentModule.Data.csproj, src/VirtoCommerce.ContentModule.FileSystem/VirtoCommerce.ContentModule.FileSystem.csproj, src/VirtoCommerce.ContentModule.Web/Scripts/content.js, src/VirtoCommerce.ContentModule.Web/VirtoCommerce.ContentModule.Web.csproj
Make store scope picker as a standard multiple selector
https://virtocommerce.atlassian.net/browse/PT-3496
=> PT-3497: Make store scope picker as a standard multiple selector

VirtoCommerce.ContentModule.Tests/VirtoCommerce.ContentModule.Tests.csproj, src/VirtoCommerce.ContentModule.Azure/AzureContentBlobOptions.cs, src/VirtoCommerce.ContentModule.Azure/AzureContentBlobStorageProvider.cs, src/VirtoCommerce.ContentModule.Azure/VirtoCommerce.ContentModule.Azure.csproj, src/VirtoCommerce.ContentModule.Core/Model/ContentFolder.cs, src/VirtoCommerce.ContentModule.Core/Services/IBlobContentStorageProvider.cs, src/VirtoCommerce.ContentModule.Core/VirtoCommerce.ContentModule.Core.csproj, src/VirtoCommerce.ContentModule.Data/ExportImport/ContentExportImport.cs, src/VirtoCommerce.ContentModule.Data/Extensions/ContentItemConverter.cs, src/VirtoCommerce.ContentModule.Data/VirtoCommerce.ContentModule.Data.csproj, src/VirtoCommerce.ContentModule.FileSystem/FileSystemContentBlobOptions.cs, src/VirtoCommerce.ContentModule.FileSystem/FileSystemContentBlobStorageProvider.cs, src/VirtoCommerce.ContentModule.FileSystem/VirtoCommerce.ContentModule.FileSystem.csproj, src/VirtoCommerce.ContentModule.Web/Controllers/Api/ContentController.cs, src/VirtoCommerce.ContentModule.Web/Module.cs, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.js, src/VirtoCommerce.ContentModule.Web/VirtoCommerce.ContentModule.Web.csproj, src/VirtoCommerce.ContentModule.Web/module.manifest
Use assets from newly created module instead of the platform
https://virtocommerce.atlassian.net/browse/PT-4135
=> PT-4135: Use assets from newly created module instead of the platform

src/VirtoCommerce.ContentModule.Web/Scripts/blades/themes/asset-upload.js, src/VirtoCommerce.ContentModule.Web/Scripts/resources/contentResource.js
Error in resource configuration appears when file upload via link URL
https://virtocommerce.atlassian.net/browse/PT-4362
=> PT-4362: Error in resource configuration appears when file upload via link URL

src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.tpl.html
=> PT-5514: Infinity scroll for metadata dynamic properties loading

src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/pages-list.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/themes/asset-list.js
https://virtocommerce.atlassian.net/browse/PT-4338
=> PT-4338: Add validation when renaming files

src/VirtoCommerce.ContentModule.Azure/AzureContentBlobStorageProvider.cs, src/VirtoCommerce.ContentModule.Azure/AzureContentBlobStorageProviderFactory.cs, src/VirtoCommerce.ContentModule.Web/Scripts/blades/themes/theme-detail.js
Fix delete folder, page or blog
https://virtocommerce.atlassian.net/browse/PT-5971
=> PT-5971: Fix delete folder, page or blog

src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.js
Fix Dynamic properties: duplicate properties
https://virtocommerce.atlassian.net/browse/PT-5930
=> PT-5930: Fix Dynamic properties: duplicate properties

src/VirtoCommerce.ContentModule.Web/Controllers/Api/ContentController.cs, src/VirtoCommerce.ContentModule.Web/module.manifest
WebClient is replaced with HttpClientFactory
https://virtocommerce.atlassian.net/browse/PT-5474
=> PT-5474: WebClient is replaced with HttpClientFactory

src/VirtoCommerce.ContentModule.Data/Model/MenuLinkEntity.cs
We need extensibility for `MenuLinkEntity `
https://virtocommerce.atlassian.net/browse/PT-6301
=> PT-6301: MenuLinkEntity extensibility

.github/workflows/main.yml, .github/workflows/publish_nugets.yml, Directory.Build.props, VirtoCommerce.ContentModule.Tests/VirtoCommerce.ContentModule.Tests.csproj, src/VirtoCommerce.ContentModule.Azure/VirtoCommerce.ContentModule.Azure.csproj, src/VirtoCommerce.ContentModule.Core/VirtoCommerce.ContentModule.Core.csproj, src/VirtoCommerce.ContentModule.Data/VirtoCommerce.ContentModule.Data.csproj, src/VirtoCommerce.ContentModule.FileSystem/VirtoCommerce.ContentModule.FileSystem.csproj, src/VirtoCommerce.ContentModule.Web/VirtoCommerce.ContentModule.Web.csproj, src/VirtoCommerce.ContentModule.Web/module.manifest
Bump .Net and EF up to 6
https://virtocommerce.atlassian.net/browse/PT-1956
=> PT-1956: Bump .Net and EF up to 6

.deployment/module/argoDeploy.json, src/VirtoCommerce.ContentModule.Web/Controllers/Api/ContentController.cs
Fix exception status when uploading file
https://virtocommerce.atlassian.net/browse/PT-4899
=> PT-4899: Fix exception status when uploading file

src/VirtoCommerce.ContentModule.FileSystem/Extensions/ServiceCollectionExtensions.cs, src/VirtoCommerce.ContentModule.Web/Module.cs
https://virtocommerce.atlassian.net/browse/PT-7477
=> PT-7477: configure ContentStorageProvider fix

src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/edit-blog.js
https://virtocommerce.atlassian.net/browse/PT-9144
=> PT-9144: skip catalog creating when creating a blog

src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.js
https://virtocommerce.atlassian.net/browse/PT-9659
=> PT-9659: copy props to orig entity

src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/edit-blog.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.tpl.html
https://virtocommerce.atlassian.net/browse/PT-9652
=> PT-9652: use every form to validate content entity

src/VirtoCommerce.ContentModule.Azure/AzureContentBlobOptions.cs, src/VirtoCommerce.ContentModule.Azure/AzureContentBlobStorageProvider.cs, src/VirtoCommerce.ContentModule.Azure/VirtoCommerce.ContentModule.Azure.csproj, src/VirtoCommerce.ContentModule.FileSystem/FileSystemContentBlobStorageProviderFactory.cs, src/VirtoCommerce.ContentModule.Web/Controllers/Api/ContentController.cs, src/VirtoCommerce.ContentModule.Web/Validators/ContentFolderValidator.cs, src/VirtoCommerce.ContentModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-10072
=> PT-10072: generate correct url for uploaded blobs

src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.js, src/VirtoCommerce.ContentModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-10707
=> PT-10707: prepare properties model for localized props

src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.js
Reverts VirtoCommerce/vc-module-content#131
Jira-link:
https://virtocommerce.atlassian.net/browse/PT-10707
Artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.212.0-pr-133-eb6f.zip
=> Revert "PT-10707: prepare properties model for localized props"

src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.js
https://virtocommerce.atlassian.net/browse/PT-10707
=> PT-10707: Save button is inactive for unchanged document

src/VirtoCommerce.ContentModule.Web/package-lock.json, src/VirtoCommerce.ContentModule.Web/package.json, src/VirtoCommerce.ContentModule.Web/webpack.config.js
feat: add nodejs-lts support
https://virtocommerce.atlassian.net/browse/PT-9395
=> PT-9395: add nodejs-lts support

src/VirtoCommerce.ContentModule.Azure/AzureContentBlobOptions.cs, src/VirtoCommerce.ContentModule.Azure/AzureContentBlobStorageProvider.cs, src/VirtoCommerce.ContentModule.Azure/VirtoCommerce.ContentModule.Azure.csproj, src/VirtoCommerce.ContentModule.Data/Services/ContentFileService.cs, src/VirtoCommerce.ContentModule.Data/Services/ContentService.cs, src/VirtoCommerce.ContentModule.Data/Services/ContentStatisticService.cs, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/edit-blog.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.js, src/VirtoCommerce.ContentModule.Web/module.manifest, src/VirtoCommerce.ContentModule.Web/package-lock.json
https://virtocommerce.atlassian.net/browse/PT-11180
=> fix azure storage approach

src/VirtoCommerce.ContentModule.Azure/AzureContentBlobStorageProvider.cs, src/VirtoCommerce.ContentModule.Web/Scripts/blades/themes/asset-list.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/themes/themes-list.js
https://virtocommerce.atlassian.net/browse/PT-11344
=> fix theme access from admin panel

src/VirtoCommerce.ContentModule.Data/Services/ContentService.cs
https://virtocommerce.atlassian.net/browse/PT-11592
=> PT-11592: generate correct url for uploaded asset

src/VirtoCommerce.ContentModule.Data/Services/ContentFileService.cs, src/VirtoCommerce.ContentModule.Data/Services/ContentPathResolver.cs
https://virtocommerce.atlassian.net/browse/PT-11902
=> use urikind to check uri

src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.js
https://virtocommerce.atlassian.net/browse/PT-11930
=> PT-11930: fix metadata property values

src/VirtoCommerce.ContentModule.Core/Model/ContentSearchCriteria.cs, src/VirtoCommerce.ContentModule.Data/Search/BaseContentItemBuilder.cs, src/VirtoCommerce.ContentModule.Data/Search/ContentItemTypeRegistrar.cs, src/VirtoCommerce.ContentModule.Data/Search/ContentSearchRequestBuilder.cs, src/VirtoCommerce.ContentModule.Data/Search/DocumentIdentifierHelper.cs, src/VirtoCommerce.ContentModule.Data/Search/FullTextContentSearchService.cs, src/VirtoCommerce.ContentModule.Data/Search/MarkdownContentItemBuilder.cs, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.js, src/VirtoCommerce.ContentModule.Web/package-lock.json
https://virtocommerce.atlassian.net/browse/PT-10865
=> Use relative URL in document ID

.editorconfig, Directory.Build.props, src/VirtoCommerce.ContentModule.Azure/VirtoCommerce.ContentModule.Azure.csproj, src/VirtoCommerce.ContentModule.Core/VirtoCommerce.ContentModule.Core.csproj, src/VirtoCommerce.ContentModule.Data.MySql/VirtoCommerce.ContentModule.Data.MySql.csproj, src/VirtoCommerce.ContentModule.Data.PostgreSql/VirtoCommerce.ContentModule.Data.PostgreSql.csproj, src/VirtoCommerce.ContentModule.Data.SqlServer/VirtoCommerce.ContentModule.Data.SqlServer.csproj, src/VirtoCommerce.ContentModule.Data/ExportImport/ContentExportImport.cs, src/VirtoCommerce.ContentModule.Data/Handlers/LogChangesChangedEventHandler.cs, src/VirtoCommerce.ContentModule.Data/Search/ContentIndexDocumentChangesProvider.cs, src/VirtoCommerce.ContentModule.Data/Search/MarkdownContentItemBuilder.cs, src/VirtoCommerce.ContentModule.Data/Services/ContentPathResolver.cs, src/VirtoCommerce.ContentModule.Data/VirtoCommerce.ContentModule.Data.csproj, src/VirtoCommerce.ContentModule.FileSystem/VirtoCommerce.ContentModule.FileSystem.csproj, src/VirtoCommerce.ContentModule.Web/Controllers/Api/ContentController.cs, src/VirtoCommerce.ContentModule.Web/Module.cs, src/VirtoCommerce.ContentModule.Web/module.manifest, tests/VirtoCommerce.ContentModule.Tests/VirtoCommerce.ContentModule.Tests.csproj
https://virtocommerce.atlassian.net/browse/PT-10449
=> PT-10449: Use updated Crud and Search services

src/VirtoCommerce.ContentModule.Data/Search/ContentSearchRequestBuilder.cs
https://virtocommerce.atlassian.net/browse/PT-13132
=> PT-13132: Fix search criteria corruption

src/VirtoCommerce.ContentModule.Data/Search/ContentIndexDocumentBuilder.cs, src/VirtoCommerce.ContentModule.Data/Services/ContentService.cs
https://virtocommerce.atlassian.net/browse/PT-12539
=> PT-12539: Fix ArgumentNullException

src/VirtoCommerce.ContentModule.Core/Events/MenuLinkListChangingEvent.cs, src/VirtoCommerce.ContentModule.Core/Extensions/MenuLinkListSearchServiceExtensions.cs, src/VirtoCommerce.ContentModule.Core/Model/MenuLinkListSearchCriteria.cs, src/VirtoCommerce.ContentModule.Core/Model/MenuLinkListSearchResult.cs, src/VirtoCommerce.ContentModule.Core/Services/IMenuLinkListSearchService.cs, src/VirtoCommerce.ContentModule.Core/Services/IMenuLinkListService.cs, src/VirtoCommerce.ContentModule.Core/Services/IMenuService.cs, src/VirtoCommerce.ContentModule.Core/VirtoCommerce.ContentModule.Core.csproj, src/VirtoCommerce.ContentModule.Data/ExportImport/ContentExportImport.cs, src/VirtoCommerce.ContentModule.Data/Model/MenuLinkListEntity.cs, src/VirtoCommerce.ContentModule.Data/Repositories/IMenuRepository.cs, src/VirtoCommerce.ContentModule.Data/Repositories/MenuRepository.cs, src/VirtoCommerce.ContentModule.Data/Services/MenuLinkListSearchService.cs, src/VirtoCommerce.ContentModule.Data/Services/MenuLinkListService.cs, src/VirtoCommerce.ContentModule.Data/Services/MenuService.cs, src/VirtoCommerce.ContentModule.Data/VirtoCommerce.ContentModule.Data.csproj, src/VirtoCommerce.ContentModule.Web/Controllers/Api/MenuController.cs, src/VirtoCommerce.ContentModule.Web/Module.cs, src/VirtoCommerce.ContentModule.Web/Scripts/blades/menu/link-lists.js, src/VirtoCommerce.ContentModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-12559
=> PT-12559: Migrate to CRUD services

src/VirtoCommerce.ContentModule.Data/Search/ContentIndexDocumentBuilder.cs
https://virtocommerce.atlassian.net/browse/PT-13027
=> PT-13027: add default indexable properties

src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.tpl.html, src/VirtoCommerce.ContentModule.Web/Scripts/blades/themes/asset-detail.tpl.html, src/VirtoCommerce.ContentModule.Web/Scripts/blades/themes/asset-list.js, src/VirtoCommerce.ContentModule.Web/package-lock.json
feat: Improve asset editor with using 100% width and height in the blade.
https://virtocommerce.atlassian.net/browse/PT-13494
=> PT-13494: Improve asset editor

src/VirtoCommerce.ContentModule.Web/Scripts/blades/menu/menu-link-list.js
https://virtocommerce.atlassian.net/browse/PT-13544
=> PT-13544: add clone link list button

src/VirtoCommerce.ContentModule.Core/Model/IndexableContentFile.cs, src/VirtoCommerce.ContentModule.Data/Search/ContentSlugResolver.cs, src/VirtoCommerce.ContentModule.Data/Search/FullTextContentSearchService.cs, src/VirtoCommerce.ContentModule.Web/Module.cs
https://virtocommerce.atlassian.net/browse/PT-13653
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.410.0-pr-159-06e0.zip
=> PT-13653: add slug resolver

src/VirtoCommerce.ContentModule.Data/Search/ContentSlugResolver.cs
Fix: Storefront fails if search content index is disabled
https://virtocommerce.atlassian.net/browse/PT-14127
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.411.0-pr-160-3454.zip
=> PT-14127: check if content indexing is disabled

Directory.Build.props, src/VirtoCommerce.ContentModule.Core/Model/ContentSearchCriteria.cs, src/VirtoCommerce.ContentModule.Data/Extensions/ContentItemConverter.cs, src/VirtoCommerce.ContentModule.Data/Search/BaseContentItemBuilder.cs, src/VirtoCommerce.ContentModule.Data/Search/ContentSearchRequestBuilder.cs, src/VirtoCommerce.ContentModule.Data/Services/ContentService.cs, src/VirtoCommerce.ContentModule.Web/Localizations/en.VirtoCommerce.Content.json, src/VirtoCommerce.ContentModule.Web/Scripts/blades/content-main.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/choose-action.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/choose-action.tpl.html, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/pages-list.js, src/VirtoCommerce.ContentModule.Web/Scripts/content.js, src/VirtoCommerce.ContentModule.Web/Scripts/resources/contentResource.js, src/VirtoCommerce.ContentModule.Web/Scripts/services/file-handler.factory.js, src/VirtoCommerce.ContentModule.Web/Scripts/services/markdown-file.handler.js, src/VirtoCommerce.ContentModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-13638
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.413.0-pr-162-cc89.zip
=> PT-13638: use folder in search index

src/VirtoCommerce.ContentModule.Core/Model/IndexableContentFile.cs, src/VirtoCommerce.ContentModule.Data/Search/ContentSlugResolver.cs, src/VirtoCommerce.ContentModule.Data/Search/FullTextContentSearchService.cs, src/VirtoCommerce.ContentModule.Data/Search/MarkdownContentItemBuilder.cs
add displayName property to index
https://virtocommerce.atlassian.net/browse/PT-14120
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.414.0-pr-163-07ea.zip
=> PT-14120: add displayName property to index

src/VirtoCommerce.ContentModule.Data/Search/BaseContentItemBuilder.cs, src/VirtoCommerce.ContentModule.Data/Search/ContentSearchRequestBuilder.cs, src/VirtoCommerce.ContentModule.Data/Search/MarkdownContentItemBuilder.cs
https://virtocommerce.atlassian.net/browse/PT-11923
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.415.0-pr-164-3207.zip
=> PT-11923: add language to index

Directory.Build.props, src/VirtoCommerce.ContentModule.Azure/VirtoCommerce.ContentModule.Azure.csproj, src/VirtoCommerce.ContentModule.Core/VirtoCommerce.ContentModule.Core.csproj, src/VirtoCommerce.ContentModule.Data.MySql/VirtoCommerce.ContentModule.Data.MySql.csproj, src/VirtoCommerce.ContentModule.Data.PostgreSql/VirtoCommerce.ContentModule.Data.PostgreSql.csproj, src/VirtoCommerce.ContentModule.Data.SqlServer/VirtoCommerce.ContentModule.Data.SqlServer.csproj, src/VirtoCommerce.ContentModule.Data/Repositories/MenuDbContext.cs, src/VirtoCommerce.ContentModule.Data/VirtoCommerce.ContentModule.Data.csproj, src/VirtoCommerce.ContentModule.FileSystem/VirtoCommerce.ContentModule.FileSystem.csproj, src/VirtoCommerce.ContentModule.Web/VirtoCommerce.ContentModule.Web.csproj, src/VirtoCommerce.ContentModule.Web/module.manifest, tests/VirtoCommerce.ContentModule.Tests/VirtoCommerce.ContentModule.Tests.csproj
https://virtocommerce.atlassian.net/browse/PT-14740
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.800.0-pr-165-3fe6.zip
=> PT-14740: .net 8

src/VirtoCommerce.ContentModule.Azure/AzureContentBlobStorageProvider.cs, src/VirtoCommerce.ContentModule.Azure/AzureContentBlobStorageProviderFactory.cs, src/VirtoCommerce.ContentModule.Azure/VirtoCommerce.ContentModule.Azure.csproj, src/VirtoCommerce.ContentModule.FileSystem/FileSystemContentBlobStorageProvider.cs, src/VirtoCommerce.ContentModule.FileSystem/FileSystemContentBlobStorageProviderFactory.cs, src/VirtoCommerce.ContentModule.FileSystem/VirtoCommerce.ContentModule.FileSystem.csproj, src/VirtoCommerce.ContentModule.Web/module.manifest
feat: Update dependency on Azure and File Assets.
https://virtocommerce.atlassian.net/browse/VCST-489
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.801.0-pr-168-b05a.zip
=> VCST-489: Update dependency on Azure and File Assets

src/VirtoCommerce.ContentModule.Data/Extensions/ContentItemConverter.cs
* Remove get parameters from urls
https://virtocommerce.atlassian.net/browse/VCST-642
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.804.0-pr-173-4da0.zip
=> VCST-642: remove get parameters from urls for given blobs

src/VirtoCommerce.ContentModule.Web/Scripts/blades/content-main.tpl.html
feat: Remove Counter from Search panel
https://virtocommerce.atlassian.net/browse/VCST-972
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.805.0-pr-174-5359.zip
=> VCST-972: Remove Counter from Search panel

src/VirtoCommerce.ContentModule.Web/Scripts/blades/content-main.tpl.html
https://virtocommerce.atlassian.net/browse/VCST-812
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.806.0-pr-175-87df.zip
=> VCST-812: add style to truncate theme name

src/VirtoCommerce.ContentModule.Azure/AzureContentBlobStorageProvider.cs, src/VirtoCommerce.ContentModule.Data.PostgreSql/VirtoCommerce.ContentModule.Data.PostgreSql.csproj, src/VirtoCommerce.ContentModule.Web/Controllers/Api/ContentController.cs, src/VirtoCommerce.ContentModule.Web/Scripts/blades/themes/theme-detail.js
* return actual theme stats
https://virtocommerce.atlassian.net/browse/VCST-1206
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.808.0-pr-177-e43b.zip
=> VCST-1206: remove cache for theme stats

src/VirtoCommerce.ContentModule.Core/Model/IndexableContentFile.cs, src/VirtoCommerce.ContentModule.Data.PostgreSql/VirtoCommerce.ContentModule.Data.PostgreSql.csproj, src/VirtoCommerce.ContentModule.Data/Extensions/ContentItemConverter.cs, src/VirtoCommerce.ContentModule.Data/Search/BaseContentItemBuilder.cs, src/VirtoCommerce.ContentModule.Data/Search/ContentSearchRequestBuilder.cs, src/VirtoCommerce.ContentModule.Data/Search/ContentSlugResolver.cs, src/VirtoCommerce.ContentModule.Data/Search/FullTextContentSearchService.cs, src/VirtoCommerce.ContentModule.Data/Services/ContentService.cs
add language to the `IndexableContentFile` class.
It allows to filter pages by required language
https://virtocommerce.atlassian.net/browse/VCST-1110
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.810.0-pr-176-532a.zip
=> VCST-1110, VCST-690: add language to index document model

src/VirtoCommerce.ContentModule.Data.PostgreSql/VirtoCommerce.ContentModule.Data.PostgreSql.csproj, src/VirtoCommerce.ContentModule.Web/Localizations/en.VirtoCommerce.Content.json, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.js
* implement publish and unpublish logic in for the md files
https://virtocommerce.atlassian.net/browse/VCST-1241
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.811.0-pr-178-ed2b.zip
=> VCST-1241: add publish/unpublish operations for md files

src/VirtoCommerce.ContentModule.Web/Scripts/blades/themes/theme-detail.tpl.html
https://virtocommerce.atlassian.net/browse/VCST-1248
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.812.0-pr-179-a907.zip
=> VCST-1248: add restriction in ui for theme name

src/VirtoCommerce.ContentModule.Core/Events/ContentFileChangedEvent.cs, src/VirtoCommerce.ContentModule.Core/Services/IPublishingService.cs, src/VirtoCommerce.ContentModule.Data/Extensions/ContentItemConverter.cs, src/VirtoCommerce.ContentModule.Data/Handlers/IndexContentChangesEventHandler.cs, src/VirtoCommerce.ContentModule.Data/Services/ContentService.cs, src/VirtoCommerce.ContentModule.Data/Services/PublishingService.cs, src/VirtoCommerce.ContentModule.Web/Controllers/Api/ContentController.cs, src/VirtoCommerce.ContentModule.Web/Module.cs, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.js
https://virtocommerce.atlassian.net/browse/VCST-1188
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.814.0-pr-181-2225.zip
=> VCST-1188: reindex files after saving

src/VirtoCommerce.ContentModule.Core/Model/IndexableContentFile.cs, src/VirtoCommerce.ContentModule.Core/Search/IFullTextContentSearchService.cs, src/VirtoCommerce.ContentModule.Core/VirtoCommerce.ContentModule.Core.csproj, src/VirtoCommerce.ContentModule.Data/Search/ContentSeoResolver.cs, src/VirtoCommerce.ContentModule.Data/Search/ContentSlugResolver.cs, src/VirtoCommerce.ContentModule.Data/Search/FullTextContentSearchService.cs, src/VirtoCommerce.ContentModule.Data/Search/MarkdownContentItemBuilder.cs, src/VirtoCommerce.ContentModule.Web/Controllers/Api/ContentController.cs, src/VirtoCommerce.ContentModule.Web/Module.cs, src/VirtoCommerce.ContentModule.Web/Scripts/resources/contentResource.js, src/VirtoCommerce.ContentModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-1363
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.815.0-pr-183-d005.zip
=> VCST-1363: search pages by permalink

src/VirtoCommerce.ContentModule.Web/Controllers/Api/ContentController.cs, src/VirtoCommerce.ContentModule.Web/Localizations/en.VirtoCommerce.Content.json, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.tpl.html, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/pages-list.js, src/VirtoCommerce.ContentModule.Web/Scripts/content.js, src/VirtoCommerce.ContentModule.Web/Scripts/services/broadcast-service.factory.js, src/VirtoCommerce.ContentModule.Web/Scripts/services/files-draft.service.js
https://virtocommerce.atlassian.net/browse/VCST-1189
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.816.0-pr-184-2b33.zip
=> VCST-1189: send and handle messages about file state

src/VirtoCommerce.ContentModule.Web/Controllers/Api/ContentController.cs
https://virtocommerce.atlassian.net/browse/VCST-1649
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.817.0-pr-185-7a49.zip
=> VCST-1649: remove folders

src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.tpl.html, src/VirtoCommerce.ContentModule.Web/Scripts/services/broadcast-service.factory.js, src/VirtoCommerce.ContentModule.Web/Scripts/services/markdown-file.handler.js
https://virtocommerce.atlassian.net/browse/VCST-1477
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.818.0-pr-186-5f81.zip
=> VCST-1477: validate form before saving

src/VirtoCommerce.ContentModule.Data/Search/ContentSeoResolver.cs, src/VirtoCommerce.ContentModule.Data/Search/DocumentIdentifierHelper.cs, src/VirtoCommerce.ContentModule.Data/Services/ContentStatisticService.cs, src/VirtoCommerce.ContentModule.Data/Services/PublishingService.cs, src/VirtoCommerce.ContentModule.Web/Controllers/Api/ContentController.cs, src/VirtoCommerce.ContentModule.Web/Scripts/blades/content-main.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.js, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/page-detail.tpl.html, src/VirtoCommerce.ContentModule.Web/Scripts/blades/pages/pages-list.js, src/VirtoCommerce.ContentModule.Web/Scripts/services/file-handler.factory.js, tests/VirtoCommerce.ContentModule.Tests/ContentStatisticServiceTests.cs, tests/VirtoCommerce.ContentModule.Tests/PublishingServiceTests.cs, tests/VirtoCommerce.ContentModule.Tests/VirtoCommerce.ContentModule.Tests.csproj
Fixed error "Store url was not configured.." when it is configured
https://virtocommerce.atlassian.net/browse/VCST-3985
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.829.0-pr-201-31a7.zip
=> VCST-3985: fix store url missing error
